export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const DELETE_CONTACTS = "DELETE_CONTACTS";
export const ADD_CONTACTS = "ADD_CONTACTS";
export const EDIT_CONTACTS = "EDIT_CONTACTS";
export const GET_CONTACT_BY_ID = "GET_CONTACT_BY_ID";